### ISSUE TITLE
"Current day Energy" not resetting each day

### ISSUE THREAD

**Issue by twooclock** [xreef/ABB_Aurora_Solar_Inverter_Library#3]
It's certainly not your software related but I'm lost! :-(

On one of mine 3 aurora inverters ET (Current day Energy) reading on some random day starts unusually high (79170) even when previous day last reading was (32966). Seems like ET is not reset correctly. Faulty firmware is C.0.0.6. Other two inverter with C.0.0.5 work fine.

Any ideas on how to solve this?
Thank you! Grazie!

**Comment by xreef** [comment]
Hi twooclock,
sorry I don't know how to fix the Inverter firmware, try to write to the ABB, probably can help you.
Bye Renzo
