### ISSUE TITLE
blog not respons

### ISSUE THREAD

**Issue by mjmokhtar** [xreef/ABB_Aurora_Solar_Inverter_Library#7]
i'm sorry mr can you share code about rs 485 https://mischianti.org/interface-arduino-esp8266-esp32-rs-485/ 
![image](https://github.com/xreef/ABB_Aurora_Solar_Inverter_Library/assets/108962994/db00ae0d-93a7-4daf-941c-1ee07d9282c6)
its happen in your blog

**Comment by xreef** [comment]
Thanks a lot, my registered user works properly, so I can't see that.
Thanks again Renzo
